# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPresentViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPresentViewController

  target 'TestPresentViewControllerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ViewControllerPresentationSpy', '~> 6.0'
  end

end
