# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuildForProd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for BuildForProd
  pod 'Alamofire' :configurations => ['STAGGING']
  target 'BuildForProdTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'BuildForProdUITests' do
    # Pods for testing
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.name = 'STAGGING'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13'
          config.build_settings['ENABLE_TESTABILITY'] = 'NO'
        end
      end
    end
  end
  
end
