# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

# remove warnings
inhibit_all_warnings!

target 'Forecast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forecast
  pod 'Moya'
  pod 'AlamofireNetworkActivityLogger'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'SwiftMessages'

  target 'ForecastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ForecastUITests' do
    # Pods for testing
  end

end
