disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - line_length
  - statement_position
  - force_cast
opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping
  # Find all the available rules by running:
  # swiftlint rules
included:
  - WW-Exercise-01
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - WW-Exercise-01/Network/URLRequest/BaseURLRequest.swift
  - WW-Exercise-01/Modules /Food/ListFoood/ViewContoller/ListFoodViewController.swift

force_unwrapping:
  severity: error # explicitly

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
