# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/el3sawy/RWPickFlavor.git'
target 'CarsPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarsPlayer
  pod 'AppCenter'
  pod 'AppCenter/Distribute'
  pod 'RWPickFlavor'
end
